invoice-scheduler:
    path: /
    controller: InvoiceSchedulerController:indexAction

users-cdrs:
  path: /users-cdrs
  controller: UsersCdrController:indexAction

billable-calls:
  path: /billable-calls
  controller: BillableCallController:indexAction

billable-calls-historic:
  path: /billable-calls-historic
  controller: BillableCallHistoricController:indexAction

call-csv-to-email:
  path: /call-csv-to-email
  controller: CallCsvController:indexAction

voicemail-messages:
  path: /voicemail-messages
  controller: VoicemailMessageController:indexAction
