services:
  _defaults:
    autowire: true
    public: false

  Ivoz\Provider\Domain\Service\RoutingPatternGroupsRelPattern\CreateAndPersist: ~

  Ivoz\Provider\Domain\Service\RoutingPatternGroup\UpdateByRoutingPatternAndCountry: ~

  Ivoz\Kam\Domain\Service\TrunksLcrRule\CreateByOutgoingRoutingAndRoutingPattern: ~

  Ivoz\Provider\Domain\Service\Invoice\Generator:
    arguments:
      $logger: '@logger'
      $vendorDir: '%kernel.project_dir%/vendor/'

  Ivoz\Provider\Domain\Service\Extension\AliasImporter:
    public: true

  Ivoz\Provider\Domain\Service\Terminal\Provision\Provision: ~
  Ivoz\Provider\Domain\Service\Terminal\Provision\ProvisionGeneric:
    arguments:
      $storagePath: '%local_storage_path%'
  Ivoz\Provider\Domain\Service\Terminal\Provision\ProvisionSpecific:
    arguments:
      $storagePath: '%local_storage_path%'