production:
  entity: Ivoz\Provider\Domain\Model\ExternalCallFilter\ExternalCallFilter
  fields:
    company:
      title: ngettext('Client', 'Clients', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: Ivoz\Provider\Domain\Model\Company\Company
          fieldName:
            fields:
              - name
            template: '%name%'
          order:
            Company.name: asc
    name:
      title: _('Name')
      type: text
      trim: both
      required: true
      default: true
    outOfScheduleEnabled:
      title: _('Unconditional Call Forward')
      type: select
      defaultValue: 0
      source:
        data: inline
        values:
          '0':
            title: _("No")
            visualFilter:
              hide: [ outOfScheduleTargetType, outOfScheduleNumberValue, outOfScheduleNumberCountry ]
              show: []
          '1':
            title: _("Yes")
            visualFilter:
              show: [ outOfScheduleTargetType, outOfScheduleNumberValue, outOfScheduleNumberCountry ]
              hide: []
    outOfScheduleNumberCountry:
      title: ngettext('Country', 'Countries', 1)
      type: select
      required: true
      source:
        data: mapper
        config:
          entity: \Ivoz\Provider\Domain\Model\Country\Country
          fieldName:
            fields:
              - name${lang}
              - countryCode
            template: '%name${lang}% (%countryCode%)'
          order:
            Country.name.${lang}: asc
    outOfScheduleNumberValue:
      title: _('Number')
      type: text
      trim: both
      required: true
    outOfScheduleTargetType:
      title: _('Out of schedule target type')
      type: select
      source:
        data: inline
        values:
          'number':
            title: _('Number')
    blackLists:
      title: _('Black Lists')
      type: multiselect
      source:
        data: mapper
        config:
          relation: \Ivoz\Provider\Domain\Model\ExternalCallFilterBlackList\ExternalCallFilterBlackList
          relationProperty: filter
          relatedProperty: matchlist
          related: \Ivoz\Provider\Domain\Model\MatchList\MatchList
          relatedFieldName: name
          filterClass: IvozProvider_Klear_Filter_CompanyOrBrand
      info:
        type: box
        text: _("Incoming numbers that match this lists will be always REJECTED without checking this filter configuration.")
        label: _("Need help?")
staging:
  _extends: production
testing:
  _extends: production
development:
  _extends: production
localdev:
  _extends: production
