########################################
## Custom models
########################################
Model\Dashboard\DashboardBillableCall:
  itemOperations: []
  collectionOperations: []

Model\Dashboard\DashboardClient:
  itemOperations: []
  collectionOperations: []

Model\Dashboard\DashboardResidentialDevice:
  itemOperations: []
  collectionOperations: []

Model\Dashboard\DashboardRetailAccount:
  itemOperations: []
  collectionOperations: []

Model\Dashboard\DashboardUser:
  itemOperations: []
  collectionOperations: []

Model\Dashboard\Dashboard:
  itemOperations:
    get_my_dasboard:
      access_control: '"ROLE_COMPANY_ADMIN" in roles && user.hasAccessPrivileges(_api_resource_class, request.getMethod())'
      method: 'GET'
      path: '/my/dashboard'
      route_name: 'get_my_dasboard'
      parameters: []
      swagger_context:
        produces:
          - 'application/json'
        tags:
          - My
  collectionOperations: []

Model\Token:
  itemOperations: []
  collectionOperations:
    post_auth_token_exchange:
      method: 'POST'
      path: '/token/exchange'
      route_name: 'post_auth_token_exchange'
      swagger_context:
        consumes:
        - 'application/x-www-form-urlencoded'
        produces:
        - 'application/json'
        tags:
        - Auth
        parameters:
        - name: token
          in: formData
          type: string
          required: true
          description: 'Brand admin token'
        - name: username
          in: formData
          type: string
          required: false
          description: 'Target client admin user name'
        - name: clientId
          in: formData
          type: integer
          required: false
          description: 'Target client ID'

Model\RatingPlanPrices:
  attributes:
    access_control: '"ROLE_COMPANY_ADMIN" in roles && user.hasAccessPrivileges(_api_resource_class, request.getMethod())'
    pagination_enabled: false
  itemOperations: []
  collectionOperations:
    get_my_rating_plan_prices:
      method: 'GET'
      path: '/rating_plan_groups/{id}/prices'
      route_name: 'get_my_rating_plan_prices'
      swagger_context:
        produces:
        - 'text/csv'
        tags:
        - Provider
        parameters:
        - name: id
          in: path
          type: integer
          required: true
          description: 'Rating plan group Id'

Model\ActiveCalls:
  itemOperations:
    get_my_active_calls:
      access_control: '"ROLE_COMPANY_ADMIN" in roles && user.hasAccessPrivileges(_api_resource_class, request.getMethod())'
      method: 'GET'
      path: '/my/active_calls'
      route_name: 'get_my_active_calls'
      swagger_context:
        produces:
        - 'application/json'
        tags:
        - My
        parameters: []
  collectionOperations: []

Model\ProfileAcl:
  itemOperations: []
  collectionOperations: []

Model\Profile:
  itemOperations:
    get_my_profile:
      access_control: '"ROLE_COMPANY_ADMIN" in roles'
      depth: 2
      method: 'GET'
      path: '/my/profile'
      route_name: 'get_my_profile'
      swagger_context:
        produces:
          - 'application/json'
        tags:
          - My
        parameters: []
  collectionOperations: []
