########################################
## Raw
########################################
Ivoz\Kam\Domain\Model\UsersLocation\RegistrationStatus:
  itemOperations: []
  collectionOperations: []
  attributes:
    normalization_context:
      groups: ['']
