api_base_path:
  path: '/'

api_admin_login:
  path: admin_login

api_user_login:
  path: user_login

###############################
## Custom routes
###############################
get_my_dasboard:
  path: '/my/dashboard'
  methods: ['GET']
  defaults:
    _controller: Controller\My\DashboardAction
    _api_resource_class: 'Model\Dashboard\Dashboard'
    _api_item_operation_name: 'get_my_dasboard'
    _api_receive: false

# required for IRI generation
get_my_dasboard_admin:
  path: '/my/dashboard_admin'
  methods: []
  defaults:
    _api_resource_class: 'Model\Dashboard\DashboardAdmin'
    _api_item_operation_name: 'get_my_dasboard_admin'

# required for IRI generation
get_my_dasboard_brand:
  path: '/my/dashboard_brand'
  methods: []
  defaults:
    _api_resource_class: 'Model\Dashboard\DashboardBrand'
    _api_item_operation_name: 'get_my_dasboard_brand'

get_my_active_calls:
  path: '/my/active_calls'
  methods: ['GET']
  defaults:
    _controller: Controller\My\ActiveCallsAction
    _api_resource_class: 'Model\ActiveCalls'
    _api_item_operation_name: 'get_my_active_calls'
    _api_receive: false

get_my_profile:
  path: '/my/profile'
  methods: ['GET']
  defaults:
    _controller: Controller\My\ProfileAction
    _api_resource_class: 'Model\Profile'
    _api_item_operation_name: 'get_my_profile'
    _api_receive: false

put_billable_call_rate_by_callid:
  path: '/billable_calls/{callid}/rate'
  methods: ['PUT']
  defaults:
    _controller: Controller\Provider\PutBillableCallRatingAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\BillableCall\BillableCall'
    _api_item_operation_name: 'put_billable_call_rate_by_callid'
    _api_receive: false

get_invoice_preview:
  path: '/invoice_templates/{id}/preview'
  methods: ['GET']
  defaults:
    _controller: Controller\Provider\InvoiceTemplatePreviewAction
    _api_item_operation_name: 'get_invoice_preview'

get_my_theme:
  path: '/my/theme'
  methods: ['GET']
  defaults:
    _controller: Controller\My\WebThemeAction
    _api_resource_class: 'Ivoz\Provider\Domain\Model\WebPortal\WebTheme'
    _api_item_operation_name: 'get_my_theme'
    _api_receive: false

get_my_logo:
  path: '/my/logo/{id}/{name}'
  methods: ['GET']
  defaults:
    _controller: Controller\My\LogoAction
    _api_item_operation_name: 'get_my_logo'
    _api_receive: false