########################################
## Custom models
########################################
Model\Dashboard\Dashboard:
  itemOperations:
    get_my_dasboard:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/dashboard'
      route_name: 'get_my_dasboard'
      parameters: []
      swagger_context:
        produces:
          - 'application/json'
        tags:
          - My
  collectionOperations: []
  
Model\LastMonthCalls:
  itemOperations:
    get_my_last_month_calls:
      access_control: '"ROLE_COMPANY_USER" in roles'
      method: 'GET'
      path: '/my/last_month_calls'
      route_name: 'get_my_last_month_calls'
      swagger_context:
        produces:
        - 'application/json'
        tags:
        - My
  collectionOperations: []

Model\UserStatus:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/status'
      route_name: 'get_my_status'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}

Model\CallStats:
  attributes:
    access_control: '"ROLE_COMPANY_USER" in roles'
  itemOperations:
    get:
      method: 'GET'
      path: '/my/call_stats'
      route_name: 'get_my_call_stats'
      swagger_context:
        tags:
          - My
        parameters: []
  collectionOperations: {}