Ivoz\Provider\Domain\Model\FixedCostsRelInvoiceScheduler\FixedCostsRelInvoiceSchedulerAbstract:
  type: mappedSuperclass
  uniqueConstraints:
    FixedCostsRelInvoiceScheduler_invoiceScheduler_fixedCost:
      columns:
      - invoiceSchedulerId
      - fixedCostId
  fields:
    quantity:
      column: quantity
      type: integer
      nullable: true
      options:
        unsigned: true
    type:
      type: string
      nullable: false
      length: 25
      options:
        fixed: false
        comment: '[enum:static|maxcalls|ddis]'
        default: 'static'
    ddisCountryMatch:
      column: ddisCountryMatch
      type: string
      nullable: true
      length: 25
      options:
        fixed: false
        comment: '[enum:all|national|international|specific]'
        default: 'all'
  manyToOne:
    fixedCost:
      targetEntity: \Ivoz\Provider\Domain\Model\FixedCost\FixedCostInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        fixedCostId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    invoiceScheduler:
      targetEntity: \Ivoz\Provider\Domain\Model\InvoiceScheduler\InvoiceSchedulerInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: relFixedCosts
      joinColumns:
        invoiceSchedulerId:
          referencedColumnName: id
          nullable: false
          onDelete: cascade
      orphanRemoval: false
    ddisCountry:
      targetEntity: \Ivoz\Provider\Domain\Model\Country\CountryInterface
      cascade: {  }
      fetch: LAZY
      mappedBy: null
      inversedBy: null
      joinColumns:
        ddisCountryId:
          referencedColumnName: id
          nullable: true
          onDelete: set null
      orphanRemoval: false
